spring:
  application:
    name: feed
  datasource:
    url: jdbc:mysql://localhost:3306/feed?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: test  # MySQL 비밀번호를 설정하세요.
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate # 운영 환경에서는 update 대신 validate나 none 사용 추천
    database: mysql
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        query:
          in_clause_parameter_padding: true
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 50
  data:
    redis:
      host: localhost
      port: 6379
logging:
  level:
    root: INFO
    org:
      hibernate.SQL: DEBUG
