spring:
  application:
    name: feed
  datasource:
    url: jdbc:h2:mem:grandatlas
    username: sa
    driverClassName: org.h2.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    database: H2
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        query:
          in_clause_parameter_padding: true
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: localhost
      port: 6379
